server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Spring configurations
spring:
  datasource:
    url: jdbc:mysql://mysqldb/order_picking_service
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  profiles:
    active: local
  application:
    name: order-picking-servic
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: orderProducer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      linger-ms: 1
      enable-Idempotence: true
      transactionalId: orderTransaction
    consumer:
      bootstrap-servers: localhost:9092
      client-id: orderConsumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      isolationLevel: read_committed
      max-poll-records: 10
      heartbeat-interval: 6000

kafka:
  topic:
    order:
      name: com-egen-bootcamp-order-picking-service
      groupId: order-picking-service-group2